### ISSUE TITLE
TypeError: Bad argument - something w/ phantomjs

### ISSUE THREAD

**Issue by tomfuertes** [clearhead/clearhead#2]
```bash
[10:27:18] Finished 'test:modules' after 1.62 s
[10:27:18] Finished 'test:compile-scripts' after 1.84 s
[10:27:18] Starting 'test:phantomjs'...
child_process.js:1136
  var err = this._handle.spawn(options);
                         ^
TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (child_process.js:1136:26)
    at exports.spawn (child_process.js:995:9)
    at Object.<anonymous> (/Users/tomfuertes/sandbox/git-repos/clearhead/node_modules/phantomjs/bin/phantomjs:22:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
[10:27:18] 'test:phantomjs' errored after 110 ms
[10:27:18] Error in plugin 'gulp-mocha-phantomjs'
test failed
[10:27:18] 'test:browser' errored after 1.96 s
[10:27:18] Error in plugin 'gulp-mocha-phantomjs'
test failed
```

**Comment by firstdayofjune** [comment]
I am receiving the exact same error.
I am testing a python/django application using selenium with phantomjs. Everything works fine during first (and sometimes second test), but once running the next, selenium prints:
```
WebDriverException: Message: Can not connect to GhostDriver on port 59852
```

If I run phantomjs from console now, I receive the same error as tomfuertes.
```
child_process.js:1136
  var err = this._handle.spawn(options);
                         ^
TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (child_process.js:1136:26)
    at exports.spawn (child_process.js:995:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/phantomjs/bin/phantomjs:22:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
```

I reinstalled phantomjs via npm (both locally and globally) but the behaviour persists.

**Comment by firstdayofjune** [comment]
Don't know if that helps, but I was receiving the exact same error.
I am testing a python/django application using selenium with phantomjs. Everything worked fine during first (and sometimes second test), but once running the next, selenium printed: 

``` WebDriverException: Message: Can not connect to GhostDriver on port 59852 ``` 

And if I ran phantomjs from console afterwards, I received the same error as you do. 
```
child_process.js:1136 var err = this._handle.spawn(options); 
                                             ^

TypeError: Bad argument 
       at TypeError (native)
       at ChildProcess.spawn (child_process.js:1136:26)
       at exports.spawn (child_process.js:995:9)
       at Object.<anonymous> (/usr/local/lib/node_modules/phantomjs/bin/phantomjs:22:10)
       at Module._compile (module.js:460:26)
       at Object.Module._extensions..js (module.js:478:10)
       at Module.load (module.js:355:320)
       at Function.Module._load (module.js:310:12)
       at Function.Module.runMain (module.js:501:10) at startup (node.js:129:16)
``` 
I tried reinstalling phantomjs via npm (both locally and globally) several times, but the behaviour persisted.

Eventually I downloaded the phantomjs bin from phantomjs.org, put that inside my /usr/local/bin and got rid of the error since!

**Comment by Manre** [comment]
Worked for me thanks

**Comment by chenchenglong** [comment]
@firstdayofjune This works fine!
